window.addEventListener('scroll', function(){
    const currentScroll = window.scrollY;
    if (Math.ceil(currentScroll) >= 0 && Math.ceil(currentScroll)< 800){
        heading.style.animationName = 'maximize'
        heading.style.animationDuration = '1s'
        heading.style.animationFillMode = 'forwards'
    }else if (Math.ceil(currentScroll) >= 800 && Math.ceil(currentScroll) < 900){
        const heading = document.getElementById('heading-one')
        heading.style.animationName = 'minimize'
    } else if (Math.ceil(currentScroll) >= 900 && Math.ceil(currentScroll) < 1000){
        const p1 = document.getElementById('p1')
        p1.style.animationName = 'max-content'
        p1.style.animationDuration = '0.5s'
        p1.style.animationFillMode = 'forwards'
    } else if (Math.ceil(currentScroll) >= 1350 && Math.ceil(currentScroll) < 1400){
        const p1 = document.getElementById('p1')
        p1.style.animationName = 'min-content';
        p1.style.animationDuration = '1s'
        p1.style.animationFillMode = 'forwards'
    } else if (Math.ceil(currentScroll) >= 1350 && Math.ceil(currentScroll) < 1450){
        const p2 = document.getElementById('p2')
        p2.style.animationName = 'max-content'
        p2.style.animationDuration = '0.5s'
        p2.style.animationFillMode = 'forwards'
    } else if (Math.ceil(currentScroll) >= 1450 && Math.ceil(currentScroll) < 1600){
        const p2 = document.getElementById('p2')
        p2.style.animationName = 'min-content';
        p2.style.animationDuration = '1s'
        p2.style.animationFillMode = 'forwards'
    } else if (Math.ceil(currentScroll) >= 1250 && Math.ceil(currentScroll) < 1300){
        const p3 = document.getElementById('p3')
        p3.style.animationName = 'max-content'
        p3.style.animationDuration = '0.5s'
        p3.style.animationFillMode = 'forwards'
    } else if (Math.ceil(currentScroll) >= 2000 && Math.ceil(currentScroll) < 2150){
        const p3 = document.getElementById('p3')
        p3.style.animationName = 'min-content';
        p3.style.animationDuration = '1s'
        p3.style.animationFillMode = 'forwards'
    } else if (Math.ceil(currentScroll) >= 1900 && Math.ceil(currentScroll) < 2300){
        const p4 = document.getElementById('p4')
        p4.style.animationName = 'max-content'
        p4.style.animationDuration = '0.5s'
        p4.style.animationFillMode = 'forwards'
    } else if (Math.ceil(currentScroll) >= 2300 && Math.ceil(currentScroll) < 2400){
        const p4 = document.getElementById('p4')
        p4.style.animationName = 'min-content';
        p4.style.animationDuration = '1s'
        p4.style.animationFillMode = 'forwards'
    } else if (Math.ceil(currentScroll) >= 2200 && Math.ceil(currentScroll) < 2300){
        const p5 = document.getElementById('p5')
        p5.style.animationName = 'max-content'
        p5.style.animationDuration = '0.5s'
        p5.style.animationFillMode = 'forwards'
    } else if (Math.ceil(currentScroll) >= 1700 && Math.ceil(currentScroll) < 1800){
        const p5 = document.getElementById('p5')
        p5.style.animationName = 'min-content';
        p5.style.animationDuration = '1s'
        p5.style.animationFillMode = 'forwards'
    } else if (Math.ceil(currentScroll) >= 1650 && Math.ceil(currentScroll) < 1700){
        const p6 = document.getElementById('p6')
        p6.style.animationName = 'max-content'
        p6.style.animationDuration = '0.5s'
        p6.style.animationFillMode = 'forwards'
    } else if (Math.ceil(currentScroll) >= 1400 && Math.ceil(currentScroll) < 1500){
        const p6 = document.getElementById('p6')
        p6.style.animationName = 'min-content';
        p6.style.animationDuration = '1s'
        p6.style.animationFillMode = 'forwards'
    }
});
const section = document.getElementsByTagName('header')[0];

section.addEventListener('mousemove', (e) =>{
  const moveX = (e.pageX * -1 / 25);
  const moveY = (e.pageY * -1 / 25);

  section.style.backgroundPosition = moveX + 'px ' + moveY + 'px';
});
const heading = document.getElementById('heading-one')
